CPPFLAGS += -Wno-unused-variable -Wno-deprecated-declarations -Wno-cpp -Wno-write-strings
#CPPFLAGS += -DMP3DEBUG
CPPFLAGS += -DDEBUG
#CPPFLAGS += -DTESTMODE
ARDUINO_LIBS = Mutila AccelStepper SoftwareSerial
BOARD_TAG = nano
BOARD_SUB = atmega328

include ../arduino.mk
