CPPFLAGS += -Wno-unused-variable -Wno-deprecated-declarations -Wno-cpp -Wno-write-strings
#CPPFLAGS += -DDEBUG
CPPFLAGS += -DDEBUG_VERBOSE
ARDUINO_LIBS = Mutila AccelStepper SoftwareSerial
BOARD_TAG = nano
BOARD_SUB = atmega328

include ../arduino.mk
