CPPFLAGS += -Wno-unused-variable -Wno-deprecated-declarations -Wno-cpp -Wno-write-strings
#CPPFLAGS += -DMUTILADEBUG
#CPPFLAGS += -DMP3DEBUG
#CPPFLAGS += -DDEBUG
#CPPFLAGS += -DENABLE_HEARTBEAT
ARDUINO_LIBS = Mutila AccelStepper SoftwareSerial EEPROM
BOARD_TAG = nano
BOARD_SUB = atmega328

include ../arduino.mk
